//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_KFC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLog
    {
        public int ActivityId { get; set; }
        public string UserType { get; set; }
        public int AccountId { get; set; }
        public string ActivityName { get; set; }
        public bool Result { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
    }
}
