//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_KFC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAccount
    {
        public int CustomerAccountId { get; set; }
        public int CustomerId { get; set; }
        public string Avatar { get; set; }
        public string AccountName { get; set; }
        public string Password { get; set; }
        public string BankAccount { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
