//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_KFC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public Employee()
        {
            this.EmployeeAccounts = new HashSet<EmployeeAccount>();
            this.Orders = new HashSet<Order>();
            this.WorkLogs = new HashSet<WorkLog>();
        }

        public int EmployeeId { get; set; }

        [Required(ErrorMessage = "Vui lòng chọn chức vụ.")]
        public int PositionId { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập tên.")]
        [StringLength(100)]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập họ.")]
        [StringLength(100)]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập ngày sinh.")]
        public DateTime Birthday { get; set; }

        [Required(ErrorMessage = "Vui lòng chọn giới tính.")]
        public bool Gender { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập số điện thoại.")]
        [Phone(ErrorMessage = "Số điện thoại không hợp lệ.")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập email.")]
        [EmailAddress(ErrorMessage = "Địa chỉ email không hợp lệ.")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập địa chỉ.")]
        public string Address { get; set; }

        public virtual ICollection<EmployeeAccount> EmployeeAccounts { get; set; }
        public virtual Position Position { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<WorkLog> WorkLogs { get; set; }
    }
}
