//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_KFC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EmployeeAccount
    {
        public int EmployeeAccountId { get; set; }
        public int EmployeeId { get; set; }
        public string Avatar { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập tên đăng nhập")]
        public string AccountName { get; set; }

        [Required(ErrorMessage = "Mật khẩu không được để trống")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
