//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_KFC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.Receipts = new HashSet<Receipt>();
        }
    
        public int InvoiceId { get; set; }
        public Nullable<int> DeliveryOrderId { get; set; }
        public Nullable<int> PromotionId { get; set; }
        public int OrderId { get; set; }
        public Nullable<int> ShippingFee { get; set; }
        public int InvoicePrice { get; set; }
        public bool Status { get; set; }
    
        public virtual DeliveryOrder DeliveryOrder { get; set; }
        public virtual Promotion Promotion { get; set; }
        public virtual Order Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt> Receipts { get; set; }
    }
}
