//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_KFC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrdersProducts = new HashSet<OrdersProduct>();
        }
    
        public int ProductId { get; set; }
        public Nullable<int> PromotionId { get; set; }
        public int ProductTypeId { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập tên món")]
        public string ProductName { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập giá tiền")]
        public int Price { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập mô tả")]
        public string Description { get; set; }

        public string ProductImage { get; set; }
        public Nullable<int> LastRating { get; set; }
        public string LastReview { get; set; }
        public Nullable<System.DateTime> LastReviewDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersProduct> OrdersProducts { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual Promotion Promotion { get; set; }
    }
}
