//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_KFC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionId { get; set; }
        public Nullable<int> StoreOrderId { get; set; }
        public string TransactionType { get; set; }
        public string TransactionName { get; set; }
        public int Amount { get; set; }
        public System.DateTime TransactionDate { get; set; }
    
        public virtual StoreOrder StoreOrder { get; set; }
    }
}
