//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_KFC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class WorkLog
    {
        public int WorkLogId { get; set; }
        public int EmployeeId { get; set; }

        [Required(ErrorMessage = "Vui lòng chọn ngày.")]
        public System.DateTime WorkDate { get; set; }
        public Nullable<System.TimeSpan> TimeIn { get; set; }
        public Nullable<System.TimeSpan> TimeOut { get; set; }

        [Required(ErrorMessage = "Vui lòng chọn ca làm việc.")]
        public string ShiftName { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
